# Generated by Django 4.1.7 on 2023-04-11 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_preference',
            field=models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Yoruba', 'Yoruba'), ('Igbo', 'Igbo')], default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in feet (e.g. 5.2)', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms (e.g. 70.5)', max_digits=5)),
                ('systolic_bp', models.PositiveIntegerField(help_text='Systolic blood pressure in mmHg (e.g. 120)')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='Diastolic blood pressure in mmHg (e.g. 80)')),
                ('heart_rate', models.PositiveIntegerField(help_text='Heart rate in beats per minute (e.g. 70)')),
                ('status', models.CharField(blank=True, help_text='Current health status (e.g. diabetes, asthma, etc.)', max_length=50, null=True)),
                ('allergies', models.CharField(blank=True, help_text='Known allergies (e.g. pollen, dust, etc.)', max_length=100, null=True)),
                ('interests', models.CharField(blank=True, help_text='Interests and hobbies (e.g. sports, music, etc.)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
