# Generated by Django 4.1.7 on 2023-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_age_profile_language_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='take_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='allergies',
            field=models.CharField(blank=True, help_text='Known allergies (e.g. pollen, dust, etc.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in Centimeters (e.g. 175.2)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='status',
            field=models.CharField(blank=True, help_text='Current health status (e.g. diabetes, asthma, etc.)', max_length=200, null=True),
        ),
    ]
