# Generated by Django 4.1.7 on 2023-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_healthdata_is_disabled_healthdata_smoke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('ig', 'Igbo')], default='en', max_length=100),
        ),
    ]
