# Generated by Django 4.1.7 on 2023-03-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
