# Generated by Django 4.1.7 on 2023-04-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
