# Generated by Django 4.1.7 on 2023-04-06 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
