# Generated by Django 4.1.7 on 2023-04-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_alter_question_category_remove_question_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discussion.community'),
        ),
    ]
